services:
  bot:
    image: pi-purchase-bot:2.0.0
    restart: always
    network_mode: host
    container_name: pi-purchase-bot
    env_file:
      - .env
    volumes:
      - ./data:/bot/data
  server-purchase:
    image: appium/appium
    container_name: appium-server-purchase
    ports:
      - 4726:4723
    privileged: true
    # network_mode: host
    restart: always
    dns:
      - 192.168.18.1
      - 192.168.18.18
    volumes:
      - /home/flappeh/.android:/home/androidusr/.android
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    environment:
      - REMOTE_ADB=true
      # - ANDROID_DEVICES=localhost:5557
      - ANDROID_DEVICES=host.docker.internal:15556
      # - DISPLAY=:1
      - REMOTE_ADB_POLLING_SEC=30
      # - APPIUM_PORT=4726
      - APPIUM_ADDITIONAL_PARAMS=--relaxed-security --allow-insecure chromedriver_autodownload --allow-insecure adb_shell(venv)
# networks:
#   appium:
#     driver: bridge
#     external: true
