services:
  docker-droid:
    image: budtmo/docker-android:emulator_9.0
    devices:
      - "/dev/kvm:/dev/kvm"
    restart: always
    container_name: android-pi
    environment:
      - APPIUM=true
      - WEB_VNC=false
      - EMULATOR_DEVICE=Nexus 4
    volumes:
      - pi-android-data_v9:/home/androidusr
    ports:
      - 4723:4723
      - 5554:5554
      - 5555:5555
      - 6080:6080
    runtime: nvidia
    deploy:
      resources:
        limits:
          cpus: 6.0
          memory: 5192M
        reservations:
          cpus: 0.25
          memory: 128M
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
volumes:
  pi-android-data_v9: