services:
  docker-droid:
    image: budtmo/docker-android:base
    devices:
      - "/dev/kvm:/dev/kvm"
    restart: always
    container_name: android-pi-nexus
    privileged: true
    environment:
      - APPIUM=true
      - WEB_VNC=false
      - WEB_LOG=false
      - EMULATOR_DEVICE=Nexus 4
      - EMULATOR_ARGS=-gpu host -accel on
      - USER_BEHAVIOR_ANALYTICS=false
      # - LD_LIBRARY_PATH=/root/emulator/lib64/qt/lib/:/root/emulator/lib64/:/root/emulator/lib64/gles_swiftshader/
    volumes:
      - pi-android-data_base:/home/androidusr
    ports:
      - 4723:4723
      - 5554:5554
      - 5555:5555
      - 6080:6080
    runtime: nvidia
    deploy:
      resources:
        limits:
          # cpus: 8.0
          memory: 5192M
        reservations:
          cpus: 0.25
          memory: 128M
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
volumes:
  pi-android-data_base: